### ISSUE TITLE
[BUG] error: '__GLIBC_MINOR__' macro redefined [-Werror,-Wmacro-redefined]

### ISSUE THREAD

**Issue by cheesetosti** [unspok3n/beatportdl#81]
### Description

When trying to build on Arch linux (glib 2.41, zig 0.14.0-dev.3287,  taglib 2.0.2-1) using `make linux-amd64`, I get an error 
```GOARCH=amd64 \
CC="zig cc -target x86_64-linux-gnu -L/usr/lib -I/usr/include -DTAGLIB_STATIC -Wall" \
CXX="zig c++ -target x86_64-linux-gnu -L/usr/lib -I/usr/include -DTAGLIB_STATIC -Wall" \
go build -ldflags "-w -linkmode external -extldflags '-lstdc++'" -buildmode pie -o=./bin/beatportdl-linux-amd64 ./cmd/beatportdl
# runtime/cgo
In file included from _cgo_export.c:3:
In file included from /usr/include/stdlib.h:26:
In file included from /usr/include/bits/libc-header-start.h:33:
/usr/include/features.h:516:9: error: '__GLIBC_MINOR__' macro redefined [-Werror,-Wmacro-redefined]
  516 | #define __GLIBC_MINOR__ 41
      |         ^
<command line>:1:9: note: previous definition is here
    1 | #define __GLIBC_MINOR__ 28
      |         ^
1 error generated.
make: *** [Makefile:42: linux-amd64] Error 1
```

### Steps To Reproduce

1. build from source for linux amd64

### OS

arch btw 

### Version

6.13.4-arch1-1 x86_64

**Comment by unspok3n** [comment]
Try specifying /usr/include with isystem
```shell
LINUX_AMD64_LIB_PATH="-L/usr/lib -isystem /usr/include" make linux-amd64
```

**Comment by cheesetosti** [comment]
:(

$ beatportdl $ LINUX_AMD64_LIB_PATH="-L/usr/lib -isystem /usr/include" make linux-amd64
Building for Linux AMD64
go clean -cache
CGO_ENABLED=1 \
GOOS=linux \
GOARCH=amd64 \
CC="zig cc -target x86_64-linux-gnu -L/usr/lib -isystem /usr/include -DTAGLIB_STATIC -Wall" \
CXX="zig c++ -target x86_64-linux-gnu -L/usr/lib -isystem /usr/include -DTAGLIB_STATIC -Wall" \
go build -ldflags "-w -linkmode external -extldflags '-lstdc++'" -buildmode pie -o=./bin/beatportdl-linux-amd64 ./cmd/beatportdl
# unspok3n/beatportdl/internal/taglib
In file included from extensions.cpp:2:
In file included from /usr/include/taglib/fileref.h:29:
In file included from /usr/include/taglib/tfile.h:29:
In file included from /usr/include/taglib/tbytevector.h:30:
In file included from /usr/lib/zig/libcxx/include/vector:325:
In file included from /usr/lib/zig/libcxx/include/__format/formatter_bool.h:17:
In file included from /usr/lib/zig/libcxx/include/__format/concepts.h:17:
In file included from /usr/lib/zig/libcxx/include/__format/format_parse_context.h:16:
In file included from /usr/lib/zig/libcxx/include/string_view:939:
In file included from /usr/lib/zig/libcxx/include/algorithm:1855:
In file included from /usr/lib/zig/libcxx/include/__algorithm/pstl_any_all_none_of.h:12:
In file included from /usr/lib/zig/libcxx/include/__algorithm/pstl_find.h:14:
In file included from /usr/lib/zig/libcxx/include/__algorithm/pstl_backend.h:12:
In file included from /usr/lib/zig/libcxx/include/__algorithm/pstl_backends/cpu_backend.h:58:
In file included from /usr/lib/zig/libcxx/include/__algorithm/pstl_backends/cpu_backends/any_of.h:14:
/usr/lib/zig/libcxx/include/__algorithm/pstl_backends/cpu_backends/backend.h:22:4: error: "Invalid CPU backend choice"
   22 | #  error "Invalid CPU backend choice"
      |    ^
1 error generated.
make: *** [Makefile:42: linux-amd64] Error 1

**Comment by unspok3n** [comment]
There's probably something wrong with your zig installation, as i can't reproduce the issue with the arch docker image. Try reinstalling zig, or manually define the cpu backend macro as a workaround:
```shell
LINUX_AMD64_LIB_PATH="-L/usr/lib -isystem /usr/include -D_LIBCPP_PSTL_CPU_BACKEND_THREAD" make linux-amd64
```

**Comment by cheesetosti** [comment]
I've built zig from source (instead of using [zig-nightly-bin](https://aur.archlinux.org/packages/zig-nightly-bin)) and was able to build it with above command!
